[lib]
proc-macro = true

[package]
name = "worm_derive"
version = "0.1.1"
edition = "2021"

[dependencies]
darling = "0.13"
dotenv = "0.15"
quote = "1"
syn = "1"
rusqlite = { version = "0.25", features = [ "bundled", "chrono" ] }
worm_core = { git = "https://github.com/frankiebaffa/worm_core" }
